name: Build Mac Binary R Packages

on:
  workflow_dispatch:
    inputs:
      r-versions:
        description: 'Comma-separated list of R versions to build for (e.g., "4.3.3,4.4.3")'
        required: false
        default: '4.4.3'
  release:
    types: [created]

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        r-version: ${{ fromJson('[' + (inputs.r-versions || '4.4.3') + ']') }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Set up R
        id: setup-r
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
          
      - name: Install R package dependencies
        run: |
          install.packages(c("remotes", "pkgbuild", "desc"))
          deps <- desc::desc_get_deps()
          pkgs <- deps[deps$type %in% c("Imports", "Depends", "LinkingTo"), "package"]
          remotes::install_cran(pkgs)
        shell: Rscript {0}
        
      - name: Build binary package
        run: R CMD INSTALL --build .
        
      - name: Set r-version variable
        run: echo "RVERSION=${{ matrix.r-version }}" >> $GITHUB_ENV

      - name: Rename macOS binary package
        run: mv beehave.go.r_*.tgz beehave.go.r_${{ env.RVERSION }}_macos_arm64.tgz
          
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: beehave.go.r_${{ env.RVERSION }}_macos_arm64.tgz